### PR TITLE
Environment Canada DS finished

### PR DESCRIPTION
**Pull request by guetteluis**

### CODE REVIEW

**Comment by terrypacker** [comment]
@guetteluis when I save the data source it disables it, this doesn't happen on other data sources.

**Comment by guetteluis** [comment]
@terrypacker I was testing now and after I enabled the DS my mango crashed. now it get stuck in 75% 
Screen Shot 2019-04-11 at 5 27 02 PM

**Comment by guetteluis** [comment]
something weird happened. I had to remove the database. I see now the error. @jazdw If you enable the DS from the list component, the `enabled` switch in DS Editor doesn't get updated. So, if you click save, it gets the the old value. This happens for all the DS:

Screen Shot 2019-04-11 at 5 43 52 PM

**Comment by jazdw** [comment]
@guetteluis When you start editing a DS (or any other item in the new UI) it creates a copy. You then edit this snapshot in time of the DS, Enabling or disabling a DS via the list on the left takes place immediately. In short what you are seeing is the intended behavior.

**Pull request merged**
