### PR TITLE
added some methods for provisioning and fixed one

### PR DESCRIPTION
**Pull request by kratosmat**
Hi all,
I have improved the API for provisioning.
I have already tested them with Virtual, Modbus and Bacnet devices.

If you have questions will not hesitate to ask me.

Bye,
Matteo.

### CODE REVIEW

**Comment by kratosmat** [comment]
Hi all,
Did you have time to check my pull request? 

Regards, 
Matteo.

**Comment by kratosmat** [comment]
Hi all, 
Did you have time to check my pull request? 
Regards, 
Matteo.

**Comment by terrypacker** [comment]
I'm going through it today.  Thanks for the help!  There are a few things I'm going to clean up so it might be worth reviewing the final code when I'm done in case you end up adding more features/changes in the future.

Cheers,
Terry

**Comment by terrypacker** [comment]
Matteo,

I want to merge this into a new branch I've created 2.7.x-sandbox.  Can you re-issue a pull request to that branch?  Then I and our test team to go over it.

Thanks again.

**Comment by kratosmat** [comment]
Hi Terry,
how can I re-issue the pull? In my fork I can't see sandbox branch....

Matteo Cusmai

**Comment by terrypacker** [comment]
I thought about that after I sent you that message.  Just leave it as is for now, we are just about to push out a new release for Mango so I didn't want to pull anything new in.  I'll leave this until next week and then pull it in.

Thanks.

**Comment by kratosmat** [comment]
Ok Terry.
One question, I am working with dglux and with dslink for mango, are you
going to update it to new api version?
I'm trying to update it, but it is very difficult...

**Comment by terrypacker** [comment]
Matteo,

I wasn't planning on it.  What exactly do you need added?  I'm not familiar enough with that code to add new UI elements.

**Comment by terrypacker** [comment]
See this commit for the adjustments made to your code to keep things more in line with the other rest controller.  Thanks for your help!

61ea3213c3beba1d4049343902596c4a5f170fe3

**Pull request merged**
